apiVersion: v1
kind: Namespace
metadata:
  name: secure-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-lister
  namespace: secure-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure-ns
  name: list-pods-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-pods-binding
  namespace: secure-ns
subjects:
- kind: ServiceAccount
  name: pod-lister
  namespace: secure-ns
roleRef:
  kind: Role
  name: list-pods-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: special-pod
  namespace: secure-ns
spec:
  serviceAccountName: pod-lister
  containers:
  - name: app
    image: alpine
    command: ["sleep", "3600"]
